name: Update Data

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Data to update'
        required: true
        default: 'exampleString'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update data in file
      run: |
        echo "Updating data to ${{ github.event.inputs.data }}"
        echo "${{ github.event.inputs.data }}" > data.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data.txt
        git commit -m "Update data to ${{ github.event.inputs.data }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
