name: Update Webpage

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'String message to display'
        required: true
        default: 'Hello, World!'

jobs:
  update-webpage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update HTML file
      run: |
        echo "<!DOCTYPE html><html><head><title>Message Display</title></head><body><h2>Temperature: ${{ github.event.inputs.message }}</h2></body></html>" > index.html

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add index.html
        git commit -m "Update webpage with message: ${{ github.event.inputs.message }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
